# Generated by Django 4.2.9 on 2024-01-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=25, verbose_name='Отчество')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название  проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние активности')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.employee', verbose_name='Рукводитель')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('deadline', models.DateField(verbose_name='Срок исполнения')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('progress', 'В работе'), ('closed', 'Закрыта')], default='new', max_length=10, verbose_name='Статус задачи')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectmanager.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.task', verbose_name='Задача')),
            ],
        ),
    ]
